// Generates the artefacts other parts of the repo consume:
//   plugins/agent-crew/lib/crew-contract.mjs   zero-dependency ESM bundle (zod inlined) for hooks and bin/crew
//   crew-contract/schemas/<name>.schema.json    JSON Schema of every artefact, for people and agents
//
// --check   regenerate into a temp dir and fail if the committed files differ (CI).
import * as esbuild from 'esbuild';
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const pkgRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = path.resolve(pkgRoot, '..');
const check = process.argv.includes('--check');
const BANNER = '// GENERATED by crew-contract/scripts/build.mjs — do not edit. Source: crew-contract/src.';

const targets = {
  bundle: path.join(repoRoot, 'plugins', 'agent-crew', 'lib', 'crew-contract.mjs'),
  schemas: path.join(pkgRoot, 'schemas'),
};

const tmp = mkdtempSync(path.join(os.tmpdir(), 'crew-contract-'));
const out = {
  bundle: check ? path.join(tmp, 'crew-contract.mjs') : targets.bundle,
  schemas: check ? path.join(tmp, 'schemas') : targets.schemas,
};

mkdirSync(path.dirname(out.bundle), { recursive: true });
await esbuild.build({
  entryPoints: [path.join(pkgRoot, 'src', 'bundle.ts')],
  outfile: out.bundle,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  banner: { js: BANNER },
  legalComments: 'none',
  minify: true,
  logLevel: 'warning',
});

// JSON Schemas come from the freshly built bundle, so they always match it.
const contract = await import(`${pathToFileURL(out.bundle).href}?t=${Date.now()}`);
const { z } = await import('zod');
rmSync(out.schemas, { recursive: true, force: true });
mkdirSync(out.schemas, { recursive: true });
for (const [name, schema] of Object.entries(contract.SCHEMAS)) {
  const json = z.toJSONSchema(schema, { unrepresentable: 'any', io: 'input' });
  json.$id = `https://github.com/Margaryan22/agent-crew/crew-contract/schemas/${name}.schema.json`;
  json.description = `agent-crew .crew/ contract v${contract.CONTRACT_VERSION}: ${name}. Cross-field rules are enforced by the Zod schema in crew-contract/src/schemas.ts.`;
  writeFileSync(path.join(out.schemas, `${name}.schema.json`), `${JSON.stringify(json, null, 2)}\n`);
}

if (check) {
  const stale = [];
  const same = (a, b) => existsSync(a) && existsSync(b) && readFileSync(a, 'utf8') === readFileSync(b, 'utf8');
  if (!same(out.bundle, targets.bundle)) stale.push(path.relative(repoRoot, targets.bundle));
  const names = new Set([...readdirSync(out.schemas), ...(existsSync(targets.schemas) ? readdirSync(targets.schemas) : [])]);
  for (const name of names) if (!same(path.join(out.schemas, name), path.join(targets.schemas, name))) stale.push(`crew-contract/schemas/${name}`);
  rmSync(tmp, { recursive: true, force: true });
  if (stale.length) {
    console.error(`Generated files are out of date:\n  ${stale.join('\n  ')}\nRun: npm run build --prefix crew-contract`);
    process.exit(1);
  }
  console.log('Generated files are up to date.');
} else {
  rmSync(tmp, { recursive: true, force: true });
  console.log(`Built ${path.relative(repoRoot, targets.bundle)} and ${Object.keys(contract.SCHEMAS).length} JSON Schemas.`);
}
